name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like and why?
    validations:
      required: true
